#!/usr/bin/env node
// Scans assets_shawarma/ and writes src/inlinedAssets.ts with every binary
// asset encoded as base64. main.ts installs a fetch interceptor that serves
// these to Pixi Assets / spine-pixi-v8 transparently, so the production
// build is a true single-file HTML (no sibling folders).
//
// Files matched: images/**/*.{png,jpg,jpeg}, sounds/**/*.mp3,
// spine_v42/**/*.{json,atlas,png}.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, extname, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..', 'assets_shawarma')
const OUT  = join(__dirname, '..', 'src', 'inlinedAssets.ts')

const MIME = {
  '.png':   'image/png',
  '.jpg':   'image/jpeg',
  '.jpeg':  'image/jpeg',
  '.mp3':   'audio/mpeg',
  '.json':  'application/json',
  '.atlas': 'text/plain',
}

function walk(dir, base) {
  const out = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const s = statSync(full)
    if (s.isDirectory()) {
      out.push(...walk(full, base))
    } else {
      const ext = extname(entry).toLowerCase()
      if (MIME[ext]) out.push({ full, rel: relative(base, full), ext })
    }
  }
  return out
}

const files = walk(ROOT, ROOT)
const entries = files.map(({ full, rel, ext }) => {
  const b64 = readFileSync(full).toString('base64')
  const key = rel.split(/[\\/]/g).join('/')
  return `  ${JSON.stringify(key)}: { mime: ${JSON.stringify(MIME[ext])}, b64: ${JSON.stringify(b64)} },`
})

const code = `// AUTO-GENERATED by scripts/inline-assets.mjs — do not edit by hand.

export type InlinedAsset = { mime: string; b64: string }

export const INLINED: Record<string, InlinedAsset> = {
${entries.join('\n')}
}
`

writeFileSync(OUT, code)
const totalBytes = files.reduce((n, f) => n + statSync(f.full).size, 0)
console.log(`[inline-assets] ${files.length} files → ${OUT} (${(totalBytes / 1024).toFixed(0)} KB raw)`)
